name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-welcome:latest .

      # Save the Docker image as a tarball for scanning
      - name: Save Docker image as tarball
        run: |
          docker save ${{ secrets.DOCKER_USERNAME }}/nginx-welcome:latest -o nginx-welcome.tar

      # Install Trend Micro Artifact Scan CLI
      - name: Install Artifact Scan CLI
        run: ./tmas_install.sh

      # Set the TMAS_API_KEY environment variable
      - name: Set TMAS_API_KEY environment variable
        run: |
          echo "export TMAS_API_KEY=${{ secrets.TMAS_API_KEY }}" >> $GITHUB_ENV

      # Scan Docker image for malware
      - name: Scan Docker image for malware
        run: tmas scan docker-archive:nginx-welcome.tar -M > scan-results.txt

      # Upload the scan results as an artifact
      - name: Upload scan results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: tmas-scan-results
          path: scan-results.txt

      # Push Docker image to Docker Hub
      - name: Push Docker image
        if: success()
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx-welcome:latest
