name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-welcome:latest .

      - name: Save Docker image as tarball
        run: docker save ${{ secrets.DOCKER_USERNAME }}/nginx-welcome:latest -o nginx-welcome.tar

      - name: Install Artifact Scan CLI
        run: ./tmas_install.sh

      # Write TMAS_API_KEY to $GITHUB_ENV so it's available for subsequent steps
      - name: Set TMAS_API_KEY environment variable
        run: echo "TMAS_API_KEY=${{ secrets.TMAS_API_KEY }}" >> $GITHUB_ENV

      - name: Scan Docker image for malware
        run: tmas scan docker-archive:nginx-welcome.tar -VSM > scan-results.txt

      - name: Upload scan results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: tmas-scan-results
          path: scan-results.txt

      - name: Push Docker image
        if: success()
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx-welcome:latest
